# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sow < Formula
  desc "AI-powered system of work - Structured software development with AI agents"
  homepage "https://github.com/jmgilman/sow"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.0/sow_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "3f552d8409965b6653156b48eec17b1014c3b6ddf2180f1d2b279be8eea26ec9"

      def install
        bin.install "sow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.0/sow_0.1.0_Darwin_arm64.tar.gz"
      sha256 "a60cf5a460ac069121deb2867773dccc36a15ba80db4cbfde70fe8c6378c5eda"

      def install
        bin.install "sow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.0/sow_0.1.0_Linux_x86_64.tar.gz"
      sha256 "45843eef40492ef1e068053bed0f104c50129368b31e4cf4d4a9828e86fd3858"
      def install
        bin.install "sow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.0/sow_0.1.0_Linux_arm64.tar.gz"
      sha256 "df20809e4c25004282be126af4610dc7179ee1bc286bd784df4955ab77f9c87a"
      def install
        bin.install "sow"
      end
    end
  end

  test do
    system "#{bin}/sow", "--version"
  end
end
