# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sow < Formula
  desc "AI-powered system of work - Structured software development with AI agents"
  homepage "https://github.com/jmgilman/sow"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.1/sow_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "53eac7f9d529e9caae9d7a0e407ab69adea833fd4a28630412b369c9e77c1857"

      def install
        bin.install "sow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.1/sow_0.1.1_Darwin_arm64.tar.gz"
      sha256 "a674277534db0609cc8cda06d33a12c2d488c1098b78aee341a58d39ff7bf781"

      def install
        bin.install "sow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.1/sow_0.1.1_Linux_x86_64.tar.gz"
      sha256 "112dbb7f4a8269d8a7f75840da9d5c1e2aa8a609f422a4b5d590cda02d336860"
      def install
        bin.install "sow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmgilman/sow/releases/download/v0.1.1/sow_0.1.1_Linux_arm64.tar.gz"
      sha256 "9ecab2e274325c2f6ca3d7ca96ba4cd911706c4649fc6b20096f13f2038e8d1e"
      def install
        bin.install "sow"
      end
    end
  end

  test do
    system "#{bin}/sow", "--version"
  end
end
