# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sow < Formula
  desc "AI-powered system of work - Structured software development with AI agents"
  homepage "https://github.com/jmgilman/sow"
  version "0.0.1-test"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/sow/releases/download/v0.0.1-test/sow_0.0.1-test_Darwin_x86_64.tar.gz"
      sha256 "e52f18cfc89eb9791c184dfdbc26625ab91335516232eaab187eea885a0da556"

      def install
        bin.install "sow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmgilman/sow/releases/download/v0.0.1-test/sow_0.0.1-test_Darwin_arm64.tar.gz"
      sha256 "4493edf3f7803ba6f8bbb28b2f496067b99f764da6bfc39059668c3e166c1c96"

      def install
        bin.install "sow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmgilman/sow/releases/download/v0.0.1-test/sow_0.0.1-test_Linux_x86_64.tar.gz"
      sha256 "a70c76d1570563f55c0e093202e18630410d81529b6df50c9bda200e6049a7f2"
      def install
        bin.install "sow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmgilman/sow/releases/download/v0.0.1-test/sow_0.0.1-test_Linux_arm64.tar.gz"
      sha256 "659561505c67eefd96e1a52416206f2ae333a3e1c53f849a0209ea4ca51cc625"
      def install
        bin.install "sow"
      end
    end
  end

  test do
    system "#{bin}/sow", "--version"
  end
end
