# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Vaultssh < Formula
  desc "Small cli wrapper for authenticating with ssh keys from hashicorp vault"
  homepage "https://github.com/jmgilman/vaultssh"
  url "https://github.com/jmgilman/vaultssh/archive/v0.1.0.tar.gz"
  sha256 "8dc45c5fc767387049fc85bca5393746c4725cf55c570971fc7a0129ff29720c"
  license "MIT"
  bottle :unneeded

  def install
    bin.install "vssh"
  end
end
