# This file was generated by GoReleaser. DO NOT EDIT.
class Vssh < Formula
  desc "A small CLI wrapper for authenticating with SSH keys from Hashicorp Vault"
  homepage "https://github.com/jmgilman/vssh"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jmgilman/vssh/releases/download/v0.1.2/vssh_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "6f9df58479482990d38c4d1c7f801dc6e8af97d93a2678b3f1a76b5f575cc9f4"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/vssh/releases/download/v0.1.2/vssh_0.1.2_Linux_x86_64.tar.gz"
      sha256 "7ad7265438a536d28ef490cef9d816de9bec719908752d1e2f1a2a4e8531d016"
    end
  end

  def install
    bin.install "vssh"
  end
end
