# This file was generated by GoReleaser. DO NOT EDIT.
class Vssh < Formula
  desc "A small CLI wrapper for authenticating with SSH keys from Hashicorp Vault"
  homepage "https://github.com/jmgilman/vssh"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jmgilman/vssh/releases/v0.1.2/vssh_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "3191cdbe340267ae62b6e772766ca07548eb49ddc2a9c379a7939d33f5883b51"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/vssh/releases/v0.1.2/vssh_0.1.2_Linux_x86_64.tar.gz"
      sha256 "794ad6155b7333300430b73c99f075ae81913519a99813336e0958b10dc91f53"
    end
  end

  def install
    bin.install "vssh"
  end
end
