# This file was generated by GoReleaser. DO NOT EDIT.
class Vssh < Formula
  desc "A small CLI wrapper for authenticating with SSH keys from Hashicorp Vault"
  homepage "https://github.com/jmgilman/vssh"
  version "0.1.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/jmgilman/vssh/releases/download/v0.1.2/vssh_0.1.2_Darwin_x86_64.tar.gz"
    sha256 "07de706b33a2b9fc776bcf4c549e4a7e61acc493202125aa2141808f17ad915a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/jmgilman/vssh/releases/download/v0.1.2/vssh_0.1.2_Linux_x86_64.tar.gz"
      sha256 "e6e77895da5b87debef8231463f65b490127ea815f9b6fc67d2ff155830d8197"
    end
  end

  def install
    bin.install "vssh"
  end
end
